# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #EDECEB
background         #1E1D1D
cursor             #BEBAB7

active_tab_foreground     #1E1D1D
active_tab_background     #EDECEB
inactive_tab_foreground   #EDECEB
inactive_tab_background   #1E1D1D

active_border_color   #EDECEB
inactive_border_color #1E1D1D
bell_border_color     #5E5A57

color0      #444343
color1		#5E5A57
color2		#6A6662
color3		#6B6662
color4		#84817D
color5		#999894
color6		#999894
color7		#DDDCDA
color8		#9B9A99
color9		#7E7874
color10		#8E8883
color11		#8E8883
color12		#B0ACA7
color13		#CCCAC6
color14		#CCCAC6
color15		#DDDCDA
