# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(1E1D1D)
$foreground = rgb(EDECEB)
$color0 = rgb(444343)
$color1 = rgb(5E5A57)
$color2 = rgb(6A6662)
$color3 = rgb(6B6662)
$color4 = rgb(84817D)
$color5 = rgb(999894)
$color6 = rgb(999894)
$color7 = rgb(DDDCDA)
$color8 = rgb(9B9A99)
$color9 = rgb(7E7874)
$color10 = rgb(8E8883)
$color11 = rgb(8E8883)
$color12 = rgb(B0ACA7)
$color13 = rgb(CCCAC6)
$color14 = rgb(CCCAC6)
$color15 = rgb(DDDCDA)
